package com.example.demo.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.ID
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.USERNAME
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.DISPLAY_NAME
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.PASSWORD
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.STATUS
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.ID
     *
     * @return the value of USERS.ID
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.ID
     *
     * @param id the value for USERS.ID
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.USERNAME
     *
     * @return the value of USERS.USERNAME
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.USERNAME
     *
     * @param username the value for USERS.USERNAME
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.DISPLAY_NAME
     *
     * @return the value of USERS.DISPLAY_NAME
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.DISPLAY_NAME
     *
     * @param displayName the value for USERS.DISPLAY_NAME
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.PASSWORD
     *
     * @return the value of USERS.PASSWORD
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.PASSWORD
     *
     * @param password the value for USERS.PASSWORD
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.STATUS
     *
     * @return the value of USERS.STATUS
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.STATUS
     *
     * @param status the value for USERS.STATUS
     *
     * @mbg.generated Tue Jul 22 17:25:36 JST 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}