version: '3.8'

services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe
    ports:
      - '1521:1521'
      - '5500:5500'
    environment:
      ORACLE_PWD: Password
      INIT_SGA_SIZE: 1028M
      INIT_PGA_SIZE: 500MB
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - ./oracle-data:/opt/oracle/oradata
    deploy:
      resources:
        limits:
          memory: 2048M

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=oracle-xe
