version: '3.8'

services:
  db:
    image: oracle/database:23.6.0-free
    container_name: demo_db
    ports:
      - 1521:1521
    volumes:
      - db-store:/opt/oracle/oradata
      - ./src/main/resources/schemas/setup:/opt/oracle/scripts/setup
    environment:
      - ORACLE_PWD=password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_app
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  db-store:
