version: '3.8'

services:
  db-source:
    image: oracle/database:23.6.0-free
    container_name: demo_db_source
    ports:
      - 1521:1521
    volumes:
      - db-source-store:/opt/oracle/oradata
      - ./src/main/resources/schemas/setup/01_init_source_db.sql:/opt/oracle/scripts/setup/01_init_source_db.sql
      - ./src/main/resources/schemas/setup/02_create_source_tables.sql:/opt/oracle/scripts/setup/02_create_tables.sql
      - ./src/main/resources/schemas/setup/03_init_source_data.sql:/opt/oracle/scripts/setup/03_init_data.sql
    environment:
      - ORACLE_PWD=password

  db-target:
    image: oracle/database:23.6.0-free
    container_name: demo_db_target
    ports:
      - 1522:1521
    volumes:
      - db-target-store:/opt/oracle/oradata
      - ./src/main/resources/schemas/setup/01_init_target_db.sql:/opt/oracle/scripts/setup/01_init_target_db.sql
      - ./src/main/resources/schemas/setup/02_create_target_tables.sql:/opt/oracle/scripts/setup/02_create_tables.sql
      - ./src/main/resources/schemas/setup/03_init_target_data.sql:/opt/oracle/scripts/setup/03_init_data.sql
    environment:
      - ORACLE_PWD=password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_app
    ports:
      - '8080:8080'
    depends_on:
      - db-source

  ogg:
    image: oracle/goldengate:23.4
    container_name: demo_ogg
    depends_on:
      - db-source
      - db-target
    volumes:
      - ./tnsnames.ora:/u01/ogg/lib/instantclient/network/admin/tnsnames.ora
      # - ./ogg_config_data:/u02/Deployment
      # - ./ogg_setup.sh:/u01/ogg/scripts/setup/ogg_setup.sh
    environment:
      # - TNS_ADMIN=/u01/ogg/lib/instantclient
      - OGG_ADMIN=oggadmin
      - OGG_ADMIN_PWD=P@ssw0rd1
      # - ORACLE_HOME=/u01/ogg
      # - ORACLE_SID=FREEPDB1
    ports:
      - '9011:9011'
      - '80:80'

volumes:
  db-source-store:
  db-target-store:
