-- PDB (Pluggable Database) にセッションを切り替える
-- FREEPDB1 は Docker イメージによって自動的に作成されるデフォルトの PDB 名
ALTER SESSION SET CONTAINER = FREEPDB1;

-- カラム名も二重引用符で囲まないことで、Oracleのデフォルトの挙動（大文字で格納）に合わせる
-- ID は NUMBER(10) で定義し、Integer にマッピングされるようにする
CREATE TABLE APPUSER.TODOS (
  ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  DUE_DATE DATE,
  COMPLETED NUMBER(1) NOT NULL
);

CREATE TABLE APPUSER.USERS (
  ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255),
  "PASSWORD" VARCHAR(30),
  "STATUS" VARCHAR(10)
);

-- シーケンス名も二重引用符で囲まないことで、Oracleのデフォルトの挙動（大文字で格納）に合わせる
CREATE SEQUENCE APPUSER.TODOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE APPUSER.USERS_SEQ START WITH 1 INCREMENT BY 1;

-- GENERATED BY DEFAULT AS IDENTITY:
-- これはOracle Database 12c 以降で導入された機能で、テーブルのカラムに自動採番のプロパティを直接付与するもの。
-- MySQLの AUTO_INCREMENT や PostgreSQL の SERIAL に似ている。
-- この設定をすると、Oracle が内部的にシーケンスとトリガーを自動で作成し、INSERT 時に ID を自動で生成してくれる。
-- アプリケーション側でシーケンス名を意識して NEXTVAL を呼び出す必要はない。

-- CREATE SEQUENCE:
-- これは Oracle Database の以前からの機能で、独立したシーケンスオブジェクトを明示的に作成するSQL文。
-- このシーケンスは、テーブルの ID 採番のためによく使われ、その場合はアプリケーションの INSERT 文で シーケンス名.NEXTVAL を明示的に呼び出す必要があった
