package com.example.demo.mapper;

import com.example.demo.entity.Todo;
import com.example.demo.entity.TodoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    long countByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    int deleteByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    int insert(Todo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    int insertSelective(Todo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    List<Todo> selectByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    Todo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    int updateByExampleSelective(@Param("row") Todo row, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    int updateByExample(@Param("row") Todo row, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    int updateByPrimaryKeySelective(Todo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TODOS
     *
     * @mbg.generated Fri Jul 18 15:51:18 JST 2025
     */
    int updateByPrimaryKey(Todo row);
}