"""
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE todos';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE todos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  due_date VARCHAR(255),
  completed NUMBER(1) NOT NULL
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  display_name VARCHAR(255),
  "password" VARCHAR(30),
  "status" VARCHAR(10)
);

INSERT INTO users (username, display_name, "password", "status") VALUES ('admin', '管理者', 'password', 'enable');
""
